# Generated by Django 6.0.4 on 2026-10-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='DNI / Documento')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono / Contacto')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo Electrónico')),
                ('observaciones_medicas', models.TextField(blank=True, default='', help_text='Apto físico, alergias, teléfono de urgencias', verbose_name='Observaciones Médicas / Contacto de Emergencia')),
                ('activo', models.BooleanField(default=True, verbose_name='Alumno Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('clases', models.ManyToManyField(blank=True, related_name='alumnos', to='actividades.actividad', verbose_name='Clases / Actividades Asignadas')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
