# Generated by Django 6.0.4 on 2026-10-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Fútbol Infantil, Gimnasia Artística, Natación', max_length=150, verbose_name='Nombre de la Actividad / Deporte')),
                ('polideportivo', models.CharField(default='Polideportivo Patricios', help_text='Ej: Polideportivo Patricios, Polideportivo Colegiales, etc.', max_length=150, verbose_name='Sede / Polideportivo')),
                ('profesor', models.CharField(blank=True, default='Prof. Mauricio Casals', max_length=150, verbose_name='Profesor a cargo')),
                ('dias_semana', models.JSONField(default=list, help_text="Lista de días de clase. Ej: ['Martes', 'Jueves', 'Viernes']", verbose_name='Días de la semana')),
                ('horario', models.CharField(help_text='Ej: 17:00, 18:00, 19:00', max_length=50, verbose_name='Franja horaria')),
                ('cupo_maximo', models.PositiveIntegerField(default=30, verbose_name='Cupo máximo de alumnos')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones / Notas')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Actividad / Clase',
                'verbose_name_plural': 'Actividades / Clases',
                'ordering': ['nombre', 'horario'],
            },
        ),
    ]
