# Generated by Django 6.0.4 on 2026-10-02 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la clase')),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente')], default='presente', max_length=20, verbose_name='Estado de Asistencia')),
                ('observacion', models.CharField(blank=True, default='', max_length=255, verbose_name='Observación particular')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='alumnos.alumno', verbose_name='Alumno')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='actividades.actividad', verbose_name='Clase / Actividad')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencias',
                'ordering': ['-fecha', 'alumno__apellido', 'alumno__nombre'],
                'unique_together': {('clase', 'alumno', 'fecha')},
            },
        ),
    ]
