# Generated by Django 6.0.4 on 2026-10-02 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado_clase', models.CharField(choices=[('normal', 'Dictada Normal'), ('suspendida_luz', 'Suspendida por Corte de Luz'), ('suspendida_clima', 'Suspendida por Clima / Lluvia'), ('feriado', 'Feriado / Sin Actividad'), ('paro', 'Medida de Fuerza / Paro'), ('otro', 'Otra Causa')], default='normal', max_length=30, verbose_name='Estado de la Jornada')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones del Docente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='actividades.actividad', verbose_name='Clase / Actividad')),
            ],
            options={
                'verbose_name': 'Novedad de Clase',
                'verbose_name_plural': 'Novedades de Clases',
                'ordering': ['-fecha', 'clase__nombre'],
                'unique_together': {('clase', 'fecha')},
            },
        ),
    ]
